// Fighter roster - all original fictional characters.
// Stats are 1-10 scale: power, speed, defense, stamina, technique
// Palette: skin, hair, trunks (primary), accent (secondary), gloves
export const ROSTER = [
  {
    id: 'kai',
    name: 'KAI',
    nickname: 'Thunder',
    style: 'Striker',
    flag: '🌊',
    weight: 'Lightweight',
    stats: { power: 6, speed: 8, defense: 6, stamina: 8, technique: 7 },
    palette: { skin: '#d8a17a', hair: '#1a1a1a', trunks: '#1862c8', accent: '#ffcc33', gloves: '#1862c8', shorts2: '#0a3a8a' },
    height: 1.0,
    build: 1.0,
    special: { name: 'THUNDER STRIKE', kind: 'flying_knee' },
    bio: 'Coastal striker with relentless tempo.',
  },
  {
    id: 'tony',
    name: 'TONY',
    nickname: 'Iron Fist',
    style: 'Boxer',
    flag: '🥊',
    weight: 'Welterweight',
    stats: { power: 9, speed: 5, defense: 7, stamina: 7, technique: 8 },
    palette: { skin: '#e6b78a', hair: '#3a2a1a', trunks: '#cc1133', accent: '#fff', gloves: '#aa0022', shorts2: '#7a0011' },
    height: 1.0,
    build: 1.05,
    special: { name: 'IRON FURY', kind: 'haymaker' },
    bio: 'Heavy hands. Each cross can end a fight.',
  },
  {
    id: 'hiro',
    name: 'HIRO',
    nickname: 'Shadow Crane',
    style: 'Karate',
    flag: '🥋',
    weight: 'Featherweight',
    stats: { power: 5, speed: 9, defense: 6, stamina: 8, technique: 9 },
    palette: { skin: '#e8c098', hair: '#0a0a0a', trunks: '#f4f4f4', accent: '#cc1133', gloves: '#222', shorts2: '#cccccc' },
    height: 0.95,
    build: 0.9,
    special: { name: 'CRANE FLURRY', kind: 'rapid_combo' },
    bio: 'Karate master, blink-and-miss footwork.',
  },
  {
    id: 'boris',
    name: 'BORIS',
    nickname: 'The Bear',
    style: 'Brawler',
    flag: '🐻',
    weight: 'Heavyweight',
    stats: { power: 10, speed: 3, defense: 8, stamina: 9, technique: 5 },
    palette: { skin: '#ddb088', hair: '#5a3a22', trunks: '#222', accent: '#cc0011', gloves: '#444', shorts2: '#0a0a0a' },
    height: 1.1,
    build: 1.25,
    special: { name: 'BEAR HUG', kind: 'slam' },
    bio: 'Mountain of a man. Never tires, never falls easy.',
  },
  {
    id: 'rafa',
    name: 'RAFA',
    nickname: 'Mamba',
    style: 'Grappler',
    flag: '🐍',
    weight: 'Middleweight',
    stats: { power: 6, speed: 7, defense: 7, stamina: 9, technique: 10 },
    palette: { skin: '#c08866', hair: '#1a0e08', trunks: '#1a8a3a', accent: '#ffcc33', gloves: '#0c5022', shorts2: '#0c5022' },
    height: 1.0,
    build: 1.0,
    special: { name: 'GUILLOTINE', kind: 'submission' },
    bio: 'Submission wizard. Catches you slipping once - it\'s over.',
  },
  {
    id: 'amir',
    name: 'AMIR',
    nickname: 'Desert Storm',
    style: 'Muay Thai',
    flag: '🌪',
    weight: 'Middleweight',
    stats: { power: 8, speed: 7, defense: 6, stamina: 8, technique: 8 },
    palette: { skin: '#c89060', hair: '#0a0a0a', trunks: '#cc9911', accent: '#000', gloves: '#aa6600', shorts2: '#7a4400' },
    height: 1.02,
    build: 1.05,
    special: { name: 'SANDSTORM ELBOW', kind: 'spinning_elbow' },
    bio: 'Eight limbs of fury - elbows, knees, shins.',
  },
  {
    id: 'jin',
    name: 'JIN',
    nickname: 'Lightning',
    style: 'Taekwondo',
    flag: '⚡',
    weight: 'Lightweight',
    stats: { power: 6, speed: 10, defense: 5, stamina: 7, technique: 9 },
    palette: { skin: '#ecc8a0', hair: '#0a0a0a', trunks: '#ffcc11', accent: '#1862c8', gloves: '#222', shorts2: '#cc8800' },
    height: 0.98,
    build: 0.92,
    special: { name: 'LIGHTNING KICK', kind: 'spin_kick' },
    bio: 'Blinding speed. Head kicks come from nowhere.',
  },
  {
    id: 'diana',
    name: 'DIANA',
    nickname: 'Phoenix',
    style: 'All-rounder',
    flag: '🔥',
    weight: 'Bantamweight',
    stats: { power: 7, speed: 8, defense: 7, stamina: 8, technique: 8 },
    palette: { skin: '#ddb088', hair: '#aa3322', trunks: '#ee5522', accent: '#ffcc33', gloves: '#cc2200', shorts2: '#aa2200' },
    height: 0.96,
    build: 0.95,
    special: { name: 'PHOENIX RISE', kind: 'rising_uppercut' },
    bio: 'Reborn from every loss, hotter every fight.',
  },
];

export function getFighter(id) {
  return ROSTER.find(f => f.id === id);
}
